### ISSUE TITLE
[Feature] Add ability to search and download

### ISSUE THREAD

**Issue by arsaboo** [mgoltzsche/beets-ytimport#1]
In addition to the likes, we could also add the ability to query YT and download. We could use the `-q` flag to specify the query. I have used something similar in the [beets-youtube](https://github.com/arsaboo/beets-youtube) plugin for metadata.

**Comment by mgoltzsche** [comment]
The `-q` option is already taken (by the `--quiet` option that is passed through to the `beet import` command) but e.g. `--search` or `--query` could be used.
How do you think the import process should look like? Would you simply import the 1st or n search results or prompt the user to confirm or select a track from multiple search results even?

**Comment by arsaboo** [comment]
`--search` sounds good. 

The last option (prompt user to confirm and select track or tracks) may be the most flexible.

**Comment by mgoltzsche** [comment]
I see. Though, selecting tracks within the browser on youtube.com is a lot more user friendly, isn't it? Correspondingly, wouldn't it make more sense to support downloading a specific Youtube playlist so that users could create a playlist of songs they want to download and use the Youtube GUI to pick songs they want to download by adding them to that playlist?

**Comment by arsaboo** [comment]
Fair enough. In that case, we can let users provide a (video or playlist) URL. No need for the users to create a playlist.

**Comment by mgoltzsche** [comment]
True and that's already working: you can provide URLs as argument to the `ytimport` command.

**Comment by mgoltzsche** [comment]
I [added an example](https://github.com/mgoltzsche/beets-ytimport/commit/08505a7818aabe52a027d4076f65af90cc340092) to the readme now.

**Comment by arsaboo** [comment]
Closing this for now. I will open another issue if I find something.
